@startuml
'https://plantuml.com/class-diagram

class User {
id: String
username: String
email: String
photo: String
password: String
contacts: ArrayList<String>
}

class Message {
id: String
sender: String
receiver: String
content: String
createdAt: DateTime
}

@enduml